

def build(bld):
    bld.DefineGem(
        # Add custom build options here
        includes    = [bld.Path('Code/CryEngine/CryAction')],
        file_list       = ['mygem.waf_files'],
        test_all_file_list = ['mygem_tests.waf_files'],
    )
