

def build(bld):
    bld.DefineGem(
        # General
        includes                = [ '.',
                                    bld.Path('Code/CryEngine/CryCommon'),
                                    bld.Path('Code/CryEngine/CryAction')],
        use                     = ['AzGameFramework'],

        # Platform Specific

        # ==============================
        # iOS
        # 'ios_output_file_name' must match both
        # 'executable_name' in 'project.json' and
        # 'Executable file' in '../Resources/IOSLauncher/Info.plist'
        # ==============================
        ios_output_file_name    = 'WafStudyLauncher',
        ios_file_list           = ['wafstudy_ios.waf_files'],

        # ==============================
        # AppleTV
        # 'appletv_output_file_name' must match both
        # 'executable_name' in 'project.json' and
        # 'Executable file' in '../Resources/AppleTVLauncher/Info.plist'
        # ==============================
        appletv_output_file_name = 'WafStudyLauncher',
        appletv_file_list       = ['wafstudy_appletv.waf_files'],

        darwin_file_list        = ['wafstudy_mac.waf_files'],

       
       

        # Testing
        test_all_file_list      = ['wafstudy_tests.waf_files'],

        # Add additional custom build options here

    )
