def build(bld):

    import os
    driver_node = bld.path.find_or_declare(
        'Gems/ScriptCanvas/Code/Include/ScriptCanvas/')
    gem_node = bld.path.find_or_declare('MyProject/Gem/Code')
    script_canvas_dir = driver_node.path_from(gem_node)

    CODEGEN_FILE_LIST = [
        'Source/ScriptCanvas/MyScriptCanvasNode.h',
    ]

    bld.DefineGem(
        # General
        includes  = [ '.',
                      bld.Path('Code/CryEngine/CryCommon'),
                      bld.Path('Code/CryEngine/CryAction')],
        use       = ['AzGameFramework','MultiplayerCharacter',
                     'ScriptCanvas'],

        # Testing
        test_all_file_list      = ['myproject_tests.waf_files'],

        # Add additional custom build options here
        win_features        = ['crcfix'],

        features        = ['az_code_gen'],
        az_code_gen = [
            {
                'files'   : CODEGEN_FILE_LIST,
                'scripts' : [os.path.join(script_canvas_dir,
                        'CodeGen/Drivers/ScriptCanvasNode.py')],
            }
        ],
    )
